# Generated by Django 5.0.1 on 2024-06-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('trade_code', models.CharField(max_length=50)),
                ('high', models.FloatField(max_length=10)),
                ('low', models.FloatField(max_length=10)),
                ('open', models.FloatField(max_length=10)),
                ('close', models.FloatField(max_length=10)),
                ('volume', models.IntegerField(max_length=50)),
            ],
        ),
    ]
