# Generated by Django 5.0.1 on 2024-06-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='close',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='high',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='low',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='open',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='volume',
            field=models.IntegerField(),
        ),
    ]
