# Generated by Django 5.0.1 on 2024-06-12 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_stock_close_alter_stock_high_alter_stock_low_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['date']},
        ),
    ]
